asset_host: http://localhost:8080
sketches_host: https://malibu-web.qtstage.io
host_to_api_host:
  help.lvh.me: https://user-documentation.quintype.io
host_to_automatic_api_host:
  - "-web"
  - ".malibu"
domain_mapping:
  subdomain.lvh.me: subdomain

publisher:
  google_tag_manager:
    id: "GTM-TP6JMSJ"
  google_analytics:
    id: "UA-139937241-1"
  onesignal:
    safari_web_id: "web.onesignal.auto.37a647a2-1bdc-46a8-a505-4f4cc6400a46"
    is_enable: true
  enableLogin: true
