asset_host: http://localhost:8080
sketches_host: https://malibu-web.qtstage.io
host_to_api_host:
  help.lvh.me: https://user-documentation.quintype.io
host_to_automatic_api_host:
  - "-web"
  - ".malibu"
domain_mapping:
  subdomain.lvh.me: subdomain

publisher:
  google_tag_manager:
    id: "GTM-TP6JMSJ"
  google_analytics:
    id: "UA-139937241-1"
  breaking_news:
    is_enable: true
    interval: 120
    item_display: 1
    open_in_new_tab: false
    pages: [home-page, section-page, tag-page, search-page, story-page, catalog-page, static-page, form-page]
  onesignal:
    safari_web_id: "web.onesignal.auto.37a647a2-1bdc-46a8-a505-4f4cc6400a46"
    is_enable: true
  enableLogin: true
